# Generated by Django 4.2.16 on 2025-05-26 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('MEN', 'MEN'), ('WOMEN', 'WOMEN'), ('SECRET', 'SECRET')], max_length=10, null=True),
        ),
    ]
